name: WORKSPHERE ci

on: 
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: |
          node -c server.js
          node -c controllers/*.js
          node -c routes/*.js
      - run: npm run lint
      - run: npm test
        env:
          GROQ_API_KEY: 'ci_dummy_key'
          JWT_SECRET: 'ci_dummy_secret'

  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build